<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class EventSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run()
    {
        $events = [
            [
                'event_name' => 'Tech Conference',
                'organizer' => 'TechWorld Inc.',
                'location' => 'New York',
                'category' => 'Technology',
                'fee' => 50.00,
                'start_date' => '2024-01-10',
                'end_date' => '2024-01-12',
                'start_time' => '09:00',
                'end_time' => '17:00',
                'description' => 'Annual technology conference.',
                'image' => 'tech-conference.jpg',
            ],
            [
                'event_name' => 'Music Festival',
                'organizer' => 'Live Nation',
                'location' => 'Los Angeles',
                'category' => 'Music',
                'fee' => 100.00,
                'start_date' => '2024-03-15',
                'end_date' => '2024-03-17',
                'start_time' => '12:00',
                'end_time' => '23:00',
                'description' => 'Live performances from top artists.',
                'image' => 'music-festival.jpg',
            ],
            [
                'event_name' => 'Art Exhibition',
                'organizer' => 'Paris Art Collective',
                'location' => 'Paris',
                'category' => 'Art',
                'fee' => 20.00,
                'start_date' => '2024-02-01',
                'end_date' => '2024-02-28',
                'start_time' => '10:00',
                'end_time' => '18:00',
                'description' => 'An exhibition showcasing modern art.',
                'image' => 'art-exhibition.jpg',
            ],
            [
                'event_name' => 'Food Expo',
                'organizer' => 'Global Gourmet',
                'location' => 'Tokyo',
                'category' => 'Food',
                'fee' => 35.00,
                'start_date' => '2024-05-05',
                'end_date' => '2024-05-07',
                'start_time' => '08:00',
                'end_time' => '20:00',
                'description' => 'Experience cuisines from around the world.',
                'image' => 'food-expo.jpg',
            ],
            [
                'event_name' => 'Startup Pitch Event',
                'organizer' => 'Innovate SF',
                'location' => 'San Francisco',
                'category' => 'Business',
                'fee' => 0.00,
                'start_date' => '2024-04-20',
                'end_date' => '2024-04-20',
                'start_time' => '10:00',
                'end_time' => '15:00',
                'description' => 'Pitch your startup to investors.',
                'image' => 'startup-pitch-event.jpg',
            ],
            [
                'event_name' => 'Book Fair',
                'organizer' => 'London Book Society',
                'location' => 'London',
                'category' => 'Literature',
                'fee' => 10.00,
                'start_date' => '2024-09-01',
                'end_date' => '2024-09-07',
                'start_time' => '09:00',
                'end_time' => '19:00',
                'description' => 'Meet your favorite authors and buy books.',
                'image' => 'book-fair.jpg',
            ],
            [
                'event_name' => 'Fashion Week',
                'organizer' => 'Milan Fashion Council',
                'location' => 'Milan',
                'category' => 'Fashion',
                'fee' => 150.00,
                'start_date' => '2024-02-10',
                'end_date' => '2024-02-14',
                'start_time' => '10:00',
                'end_time' => '18:00',
                'description' => 'The latest trends in fashion.',
                'image' => 'fashion-week.jpg',
            ],
            [
                'event_name' => 'Marathon',
                'organizer' => 'Berlin Sports Association',
                'location' => 'Berlin',
                'category' => 'Sport',
                'fee' => 25.00,
                'start_date' => '2024-11-12',
                'end_date' => '2024-11-12',
                'start_time' => '06:00',
                'end_time' => '14:00',
                'description' => 'Run through the city.',
                'image' => 'marathon.jpg',
            ],
            [
                'event_name' => 'Film Festival',
                'organizer' => 'Cannes Film Society',
                'location' => 'Cannes',
                'category' => 'Film',
                'fee' => 75.00,
                'start_date' => '2024-05-10',
                'end_date' => '2024-05-20',
                'start_time' => '14:00',
                'end_time' => '23:00',
                'description' => 'Premieres of independent films.',
                'image' => 'film-festival.jpg',
            ],
            [
                'event_name' => 'Gaming Convention',
                'organizer' => 'GamerWorld',
                'location' => 'Las Vegas',
                'category' => 'Gaming',
                'fee' => 60.00,
                'start_date' => '2024-07-18',
                'end_date' => '2024-07-20',
                'start_time' => '10:00',
                'end_time' => '19:00',
                'description' => 'The largest gaming convention in the world.',
                'image' => 'gaming-convention.jpg',
            ],
            [
                'event_name' => 'Tech Innovation Summit',
                'organizer' => 'Global Tech Solutions',
                'location' => 'Seoul',
                'category' => 'Technology',
                'fee' => 85.00,
                'start_date' => '2024-08-20',
                'end_date' => '2024-08-22',
                'start_time' => '09:00',
                'end_time' => '17:00',
                'description' => 'Showcase of the latest innovations in technology.',
                'image' => 'tech-innovation-summit.jpg',
            ],
            [
                'event_name' => 'International Dance Festival',
                'organizer' => 'World Dance Federation',
                'location' => 'Rio de Janeiro',
                'category' => 'Dance',
                'fee' => 60.00,
                'start_date' => '2024-09-25',
                'end_date' => '2024-09-27',
                'start_time' => '10:00',
                'end_time' => '22:00',
                'description' => 'A celebration of dance from around the globe.',
                'image' => 'international-dance-festival.jpg',
            ],
            [
                'event_name' => 'Health & Wellness Expo',
                'organizer' => 'FitLife Organization',
                'location' => 'Toronto',
                'category' => 'Health',
                'fee' => 40.00,
                'start_date' => '2024-06-10',
                'end_date' => '2024-06-12',
                'start_time' => '09:00',
                'end_time' => '18:00',
                'description' => 'Discover the latest trends in health and wellness.',
                'image' => 'health-wellness-expo.jpg',
            ],
            [
                'event_name' => 'Photography Awards',
                'organizer' => 'PhotoWorld',
                'location' => 'Amsterdam',
                'category' => 'Photography',
                'fee' => 30.00,
                'start_date' => '2024-11-05',
                'end_date' => '2024-11-07',
                'start_time' => '10:00',
                'end_time' => '20:00',
                'description' => 'An awards ceremony for the best in photography.',
                'image' => 'photography-awards.jpg',
            ],
            [
                'event_name' => 'Blockchain Expo',
                'organizer' => 'CryptoConferences',
                'location' => 'Dubai',
                'category' => 'Technology',
                'fee' => 70.00,
                'start_date' => '2024-05-15',
                'end_date' => '2024-05-17',
                'start_time' => '09:00',
                'end_time' => '17:00',
                'description' => 'Explore the future of blockchain technology.',
                'image' => 'blockchain-expo.jpg',
            ],
            [
                'event_name' => 'International Film Awards',
                'organizer' => 'CinemaWorld',
                'location' => 'Berlin',
                'category' => 'Film',
                'fee' => 100.00,
                'start_date' => '2024-02-25',
                'end_date' => '2024-02-27',
                'start_time' => '18:00',
                'end_time' => '23:00',
                'description' => 'Recognizing excellence in international cinema.',
                'image' => 'international-film-awards.jpg',
            ],
            [
                'event_name' => 'E-Sports Championship',
                'organizer' => 'ProGaming League',
                'location' => 'Shanghai',
                'category' => 'Gaming',
                'fee' => 50.00,
                'start_date' => '2024-07-05',
                'end_date' => '2024-07-07',
                'start_time' => '10:00',
                'end_time' => '20:00',
                'description' => 'The ultimate competition for e-sports athletes.',
                'image' => 'e-sports-championship.jpg',
            ],
            [
                'event_name' => 'Sustainable Energy Expo',
                'organizer' => 'EcoTech Innovations',
                'location' => 'Stockholm',
                'category' => 'Technology',
                'fee' => 45.00,
                'start_date' => '2024-10-15',
                'end_date' => '2024-10-17',
                'start_time' => '09:00',
                'end_time' => '17:00',
                'description' => 'Explore innovations in renewable energy.',
                'image' => 'sustainable-energy-expo.jpg',
            ],
            [
                'event_name' => 'Adventure Sports Festival',
                'organizer' => 'Outdoor Adventures',
                'location' => 'Aspen',
                'category' => 'Sport',
                'fee' => 80.00,
                'start_date' => '2024-06-01',
                'end_date' => '2024-06-03',
                'start_time' => '08:00',
                'end_time' => '18:00',
                'description' => 'An adrenaline-packed festival for adventure sports enthusiasts.',
                'image' => 'adventure-sports-festival.jpg',
            ],
            [
                'event_name' => 'Culinary Delights Festival',
                'organizer' => 'World Food Association',
                'location' => 'Mexico City',
                'category' => 'Food',
                'fee' => 50.00,
                'start_date' => '2024-09-15',
                'end_date' => '2024-09-17',
                'start_time' => '11:00',
                'end_time' => '22:00',
                'description' => 'Savor delicious cuisines from around the world.',
                'image' => 'culinary-delights-festival.jpg',
            ],
            
        ];

        DB::table('events')->insert($events);
    }
}
